### PR TITLE
[sailfish-secrets] Export lists to QML from PluginInfoRequest.

### PR DESCRIPTION
**Pull request by dcaliste**
As for #140, add wrappers for PluginInfoRequest so that the list attributes are available from QML.

@chriadam and @venemo, any remarks?

### CODE REVIEW

**Comment by chriadam** [comment]
LGTM

**Comment by dcaliste** [comment]
@chriadam do you think it can go in, or do you have any refrains on using it? Or it just went out of scope ;)

**Comment by dcaliste** [comment]
@Venemo there is this one also, if you agree.

**Comment by Venemo** [comment]
@dcaliste Merged. Have a nice day!

**Comment by dcaliste** [comment]
@Venemo great, thank you.

**Pull request merged**
