### PR TITLE
Adjust various things to be able to use FindSecretsRequest from QML

### PR DESCRIPTION
**Pull request by dcaliste**
Adapt the code from StoredKeyIdentifiersRequest from Crypto to be able to list secret identifiers with FindSecretsRequest.

### CODE REVIEW

**Comment by dcaliste** [comment]
@chriadam or @Venemo, any remarks ?

**Comment by Venemo** [comment]
@dcaliste I've looked through your changes. Looks good to me, but I don't see why exactly you needed to wrap the FindSecretsRequest, ie. what was wrong with it?

**Comment by dcaliste** [comment]
Thanks for looking into this. It's exactly like Crypto/StoredKeyIdentifiersRequest. The identifiers output property is a list of Secrets::Secret::Identifier (_resp._ Crypto::Key::Identifier). But the Identifier class is not Q_GADGET and not exposable to QML (as far as I've understood it). Without the PR, a successfull request returning a list of two secrets for instance has a length shown as ```undefined``` from QML.

Maybe there is a better way to expose the identifiers property to QML, but I'm not an expert and just sheepishly followed what has been done for the crypto equivalent.

**Comment by dcaliste** [comment]
It's fine with me. It's quite clear and it works transparently from QML.

**Comment by dcaliste** [comment]
@venemo I've #139 that looks a bit the same, handling identifiers as input for some crypto requests, if you have time to look at ;)

**Comment by Venemo** [comment]
@dcaliste Sure, will look at that too! :)

**Pull request merged**
