### PR TITLE
Add an error message when plugin cannot be loaded.

### PR DESCRIPTION
**Pull request by dcaliste**
It helps to find the root cause of a plugin not loading, like missing symbols…

### CODE REVIEW

**Comment by vityafx** [comment]
Could you provide an example of how useful it is? I mean, any output of missing symbols? I am very interested in this PR and what is actually does.

**Comment by dcaliste** [comment]
You are developing a plugin and you forgot to link it with dependencies in the pro file. It will compiles but there will be unresolved symbols on load. Or you forgot to implement some virtual methods, it will compile but will also have some unresolved symbols.

See my comment on #15 for example. It took me 30 minutes to figure out why the plugin was not initialising, while with the message I would have found it on the go:
<pre>
[W] unknown:0 - cannot load plugin: "libsailfishsecrets-passwordagentauth.so" "Cannot load library /usr/lib/Sailfish/Secrets/libsailfishsecrets-passwordagentauth.so: (/usr/lib/Sailfish/Secrets/libsailfishsecrets-passwordagentauth.so: undefined symbol: _ZN8Sailfish7Secrets6Daemon7Plugins19PasswordAgentPlugin19beginAuthenticationEjx)"
</pre>

This MR is not a life changer neither correct a bug, but it makes life easier I guess when encountering small mistakes like that.

**Comment by chriadam** [comment]
LGTM but can you please add the same also to the crypto plugin loading code, for symmetry?

**Comment by vityafx** [comment]
I'd suggest not to copy-paste the code, but have a code-reuse in use: just put plugin loading in a common place and use this code from both places.

**Comment by dcaliste** [comment]
@chriadam I've done the symmetric in crypto plugin handler.

@vityafx I've added a plugin helper to factorise the code from both secret and crypto handlers. Since it's private, I didn't put any namespace, if both of you think that it's better with, I'll update.

**Comment by vityafx** [comment]
@chriadam can we merge this so I may use these changes for my `initialise` method?

**Comment by chriadam** [comment]
LGTM thanks!

**Comment by chriadam** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x00000010 in ?? ()
(gdb) bt
#0  0x00000010 in ?? ()
#1  0x00045f8c in qobject_cast<Sailfish::Secrets::EncryptedStoragePlugin*> (object=object@entry=0xb26a8) at ../lib/Secrets/extensionplugins.h:300
#2  PluginHelper::storeAs<Sailfish::Secrets::EncryptedStoragePlugin> (this=this@entry=0xbefff2f8, obj=obj@entry=0xb26a8, store=store@entry=0x9e984, 
    category=category@entry=0x20399 <lcSailfishSecretsDaemon()>) at ./plugin_p.h:29
#3  0x00035c1e in Sailfish::Secrets::Daemon::ApiImpl::RequestProcessor::loadPlugins (this=this@entry=0x9e968, pluginDir=...)
    at SecretsImpl/secretsrequestprocessor.cpp:106
#4  0x00025ad2 in Sailfish::Secrets::Daemon::ApiImpl::SecretsRequestQueue::SecretsRequestQueue (this=0x936a8, parent=<optimized out>, pluginDir=..., 
    autotestMode=<optimized out>) at SecretsImpl/secrets.cpp:327
#5  0x0001ccea in Sailfish::Secrets::Daemon::Controller::Controller (this=0xbefff548, secretsPluginDir=..., cryptoPluginDir=..., 
    autotestMode=<optimized out>, parent=0x0) at controller.cpp:52
#6  0x0001c834 in main (argc=2, argv=<optimized out>) at main.cpp:38

**Pull request merged**
