### PR TITLE
[sailfish-secrets] Remove QtGui linkage. Contributes to JB#36025

### PR DESCRIPTION
**Pull request by chriadam**

### CODE REVIEW

**Comment by jpetrell** [comment]
LGTM

**Comment by dcaliste** [comment]
Fine, just a simple question: why is it required in qml/Secrets/Secrets.pro? I was thinking that Qt+=quick was enough for QQuickItem.

**Comment by Venemo** [comment]
Instead of `QT -= gui` why not `QT = ...` ?

**Comment by chriadam** [comment]
@dcaliste quick implies gui, so not strictly required, but also not harmful
@Venemo in case some included .pri conditionally adds support for something, better to use -= to avoid clobbering entire dependency list

**Comment by adenexter** [comment]
> in case some included .pri conditionally adds support for something, better to use -= to avoid clobbering entire dependency list

That's why you put the QT = statement before any includes. If one of those .pri files adds gui you're still clobbering that but only one instance of two assuming it was added with += and not *=.

**Comment by chriadam** [comment]
Fair point.  I've now rearranged those .pros so that the Qt modules are defined prior to any pri inclusion.

**Pull request merged**
